# Generated by Django 3.2.5 on 2021-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='limit_currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='limit_native',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='limit_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='native_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='nft_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userbot',
            name='token_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='AeN0t76RkRmrUJlD_hbcAA8eIffYl7l9Mg', max_length=100),
        ),
    ]
