# Generated by Django 3.2.5 on 2021-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210812_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='5XpSJjXiVK_zgDn81pwnXO4ZgXCVphsB5w', max_length=100),
        ),
    ]
