# Generated by Django 3.2.5 on 2021-08-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='1hrr1JISMZtp9hrLzyAj1HT0CnWZ2-DREw', max_length=100),
        ),
    ]
