# Generated by Django 3.2.5 on 2021-08-14 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210812_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_timestamp', models.IntegerField(blank=True, null=True)),
                ('end_timestamp', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('address', 'wallet')},
            },
        ),
        migrations.DeleteModel(
            name='StatsFilter',
        ),
    ]
