# Generated by Django 3.2.5 on 2021-08-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20210814_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='show_balance',
            field=models.BooleanField(default=True),
        ),
    ]
